graph TD
  GCS["Data ingestion"] --> EMBC
  subgraph EMBC["Vector Embedding"]
    DOCUP["Document pre-processing <br/> Langchain document loaders"]-->CHNK
    CHNK["Langchain text splitters"]-->EMB
    EMB["Vector Embedding <br/> postresql pgvector extension"]
  end
  subgraph RAGPL["RAG Pipeline"]
    R["Retreival <br/> input query --> top-k relevant chunks (pgvector similarity search)"] -->A
    A["Augmentation <br/> input query + pgvector chunks --> context + question(input query) template(LCEL langchain expression language)"] -->G
    G["Generation <br/> context + question template (ChatVertexAI) --> LLM (External or Internal Gemini) answer "]
  end
  subgraph MCP["MCP functionality"]
    USR["user question"] --> MCPC
    MCPC["MCP Client"] --> RAGPPL
    %% RAGPPL["RAG Pipeline"]
  end
  subgraph RAGPPL ["RAG Pipeline"]
    OAUTH["API key/ Oauth/ OIDC"] --> RAGP
    RAGP["RAG pipline"] --> FLT
    FLT["RAGAS Safety Filters"]
  end
  subgraph OBSV["GCP observability suite <br/> Logging enabled on the pipeline"]
  end

EMBC --> RAGPL --> MCP --> RAGPPL --> OBSV