# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/mcp-server-repo/mcp-server:latest', '.']
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'europe-west4-docker.pkg.dev/$PROJECT_ID/mcp-server-repo/mcp-server:latest']
# images:
#   - 'europe-west4-docker.pkg.dev/$PROJECT_ID/mcp-server-repo/mcp-server:latest'
#############
# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/mcp-server-repo/mcp-server:latest', '.']
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'europe-west4-docker.pkg.dev/$PROJECT_ID/mcp-server-repo/mcp-server:latest']
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: gcloud
#     args:
#       - 'run'
#       - 'deploy'
#       - 'rag-pipe-mcp-mcp-server'
#       - '--image=europe-west4-docker.pkg.dev/$PROJECT_ID/mcp-server-repo/mcp-server:latest'
#       - '--region=europe-west4'
# images:
#   - 'europe-west4-docker.pkg.dev/$PROJECT_ID/mcp-server-repo/mcp-server:latest'
# options:
#   logging: CLOUD_LOGGING_ONLY
################
steps:
  - name: 'ubuntu'
    args: ['find', '/workspace', '-maxdepth', '2']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/mcp-server-repo/mcp-server:latest', './projects/RAG pipeline/pipeline']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/$PROJECT_ID/mcp-server-repo/mcp-server:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rag-pipe-mcp-mcp-server'
      - '--image=europe-west4-docker.pkg.dev/$PROJECT_ID/mcp-server-repo/mcp-server:latest'
      - '--region=europe-west4'
images:
  - 'europe-west4-docker.pkg.dev/$PROJECT_ID/mcp-server-repo/mcp-server:latest'
options:
  logging: CLOUD_LOGGING_ONLY